title: Saurabh Yadav
url: "https://saurabh919yadav.github.io"
baseurl: "index"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/saurabh919yadav"
footer_text: ""

remote_theme: ankitsultana/researcher@gem
sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
